on:
  push:
    branches:
      - main
      - master
      - github-actions

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "3.1.x"
      - name: welcome
        run: echo "welcome from job"
      - name: build
        run: dotnet build ActionsKataExample
      - name: test
        run: dotnet test ActionsKataExample.Test
